const projects = [
    {
        id: 1,
        title: "first website of my life",
        description: "this is the first website i have created.",
        thumbnail: "bata_shoes.png",
        approx_date: "02/08/2020",
        keywords: ['html','css'],
        source_code: "https://codepen.io/manish202/pen/JjGgVvL",
        live_preview: "https://codepen.io/manish202/full/JjGgVvL",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 2,
        title: "live analog clock",
        description: "created simple live analog clock using html, css and javascript",
        thumbnail: "analog_clock.png",
        approx_date: "09/08/2020",
        keywords: ['html','css','javascript'],
        source_code: "https://codepen.io/manish202/pen/YzqXpGL",
        live_preview: "https://codepen.io/manish202/full/YzqXpGL",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 3,
        title: "css button animation",
        description: "created simple button animation using html and css",
        thumbnail: "button_animation.png",
        approx_date: "10/08/2020",
        keywords: ['html','css'],
        source_code: "https://codepen.io/manish202/pen/jOqPxBp",
        live_preview: "https://codepen.io/manish202/full/jOqPxBp",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 4,
        title: "slider without javascript",
        description: "created slider using html and css only, no javascript.",
        thumbnail: "slider.png",
        approx_date: "12/08/2020",
        keywords: ['html','css'],
        source_code: "https://codepen.io/manish202/pen/NWNGorE",
        live_preview: "https://codepen.io/manish202/full/NWNGorE",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 5,
        title: "simple animation",
        description: "created simple animation using html, css, javascript",
        thumbnail: "js_anim.png",
        approx_date: "14/08/2020",
        keywords: ['html','css','javascript'],
        source_code: "https://codepen.io/manish202/pen/poyyzwG",
        live_preview: "https://codepen.io/manish202/full/poyyzwG",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 6,
        title: "html css hover animation",
        description: "created simple html and css hover animation",
        thumbnail: "css_hover.png",
        approx_date: "16/08/2020",
        keywords: ['html','css'],
        source_code: "https://codepen.io/manish202/pen/wvGGXQx",
        live_preview: "https://codepen.io/manish202/full/wvGGXQx",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 7,
        title: "basic clothing webpage",
        description: "created simple clothing webpage using html and css only.",
        thumbnail: "cloth_website.png",
        approx_date: "17/08/2020",
        keywords: ['html','css'],
        source_code: "https://codepen.io/manish202/pen/VwajeMN",
        live_preview: "https://codepen.io/manish202/full/VwajeMN",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 8,
        title: "fitness landing page",
        description: "created simple fitness landing page using html, css and javascript.",
        thumbnail: "fitness.png",
        approx_date: "11/09/2020",
        keywords: ['html','css','javascript'],
        source_code: "https://codepen.io/manish202/pen/OJNZLYN",
        live_preview: "https://codepen.io/manish202/full/OJNZLYN",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 9,
        title: "digital studio webpage",
        description: "created simple webpage using html, css and jquery.",
        thumbnail: "digital_studio.png",
        approx_date: "13/09/2020",
        keywords: ['html','css','javascript','jquery'],
        source_code: "https://codepen.io/manish202/pen/WNwJBpN",
        live_preview: "https://codepen.io/manish202/full/WNwJBpN",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 10,
        title: "education mp4",
        description: "created simple webpage using html, css, jquery",
        thumbnail: "ed_mp4.png",
        approx_date: "21/09/2020",
        keywords: ['html','css','javascript','jquery'],
        source_code: "https://codepen.io/manish202/pen/oNxQzVK",
        live_preview: "https://codepen.io/manish202/full/oNxQzVK",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 11,
        title: "css js animation",
        description: "created simple animation using html, css and javascript",
        thumbnail: "js_anim2.png",
        approx_date: "22/09/2020",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/ZEWmZBK",
        live_preview: "https://codepen.io/manish202/full/ZEWmZBK",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 12,
        title: "splendorous website",
        description: "created simple webpage using html, css and javascript",
        thumbnail: "splendorous.png",
        approx_date: "15/10/2020",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/GRqoGvL",
        live_preview: "https://codepen.io/manish202/full/GRqoGvL",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 13,
        title: "chillaid website",
        description: "created simple webpage using html, css and javascript",
        thumbnail: "chillaid.png",
        approx_date: "29/10/2020",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/qBNxKLR",
        live_preview: "https://codepen.io/manish202/full/qBNxKLR",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 14,
        title: "the modernist website",
        description: "created simple webpage using html, css and javascript",
        thumbnail: "modernist.png",
        approx_date: "02/11/2020",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/ZEOoRPP",
        live_preview: "https://codepen.io/manish202/full/ZEOoRPP",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 15,
        title: "klassy restaurants",
        description: "restaurant website using bootstrap, jquery and owl carousel",
        thumbnail: "klassy.png",
        approx_date: "26/11/2020",
        keywords: ['html', 'css', 'bootstrap', 'javascript', 'jquery', 'owl carousel'],
        source_code: "https://codepen.io/manish202/pen/bGwGprP",
        live_preview: "https://codepen.io/manish202/full/bGwGprP",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 16,
        title: "fashion hub clothing site",
        description: "this is my first repo on github",
        thumbnail: "fashionhub.png",
        approx_date: "16/12/2020",
        keywords: ['html', 'css', 'bootstrap', 'javascript', 'jquery', 'aos'],
        source_code: "https://github.com/manish202/fashion-hub",
        live_preview: "https://manish202.github.io/fashion-hub/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 17,
        title: "covid 19 api",
        description: "simple covid 19 api project",
        thumbnail: "covid.png",
        approx_date: "05/01/2021",
        keywords: ['html','css','javascript','jquery'],
        source_code: "https://github.com/manish202/covid-19-api",
        live_preview: "https://manish202.github.io/covid-19-api/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 18,
        title: "blogging",
        description: "simple blogging webpage",
        thumbnail: "sora24.png",
        approx_date: "23/02/2021",
        keywords: ['html','css','bootstrap','javascript','jquery'],
        source_code: "https://github.com/manish202/blogging",
        live_preview: "https://manish202.github.io/blogging/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 19,
        title: "random color generator",
        description: "created random color generator webpage using html, css and javascript",
        thumbnail: "color_gen.png",
        approx_date: "13/03/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/QWGYJRe",
        live_preview: "https://codepen.io/manish202/full/QWGYJRe",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 20,
        title: "clock in chart format",
        description: "clock in chart format created using html, css and javascript",
        thumbnail: "chart-clock.png",
        approx_date: "14/03/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/VwmRKGV",
        live_preview: "https://codepen.io/manish202/full/VwmRKGV",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 21,
        title: "quiz api with fetch method",
        description: "quiz api with fetch method using html, css, javascript",
        thumbnail: "quiz_api.png",
        approx_date: "15/03/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/BaQbbpm",
        live_preview: "https://codepen.io/manish202/full/BaQbbpm",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 22,
        title: "depended apis",
        description: "depended apis using html, css and javascript",
        thumbnail: "fun_app.png",
        approx_date: "18/03/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/OJbGZRo",
        live_preview: "https://codepen.io/manish202/full/OJbGZRo",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 23,
        title: "card hover, dropdown etc..",
        description: "created ui components like card hover, dropdown, tabs and accordions using html, css and javascript",
        thumbnail: "card_hover.png",
        approx_date: "22/03/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/gOgYWVZ",
        live_preview: "https://codepen.io/manish202/full/gOgYWVZ",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 24,
        title: "glassmorphism animation",
        description: "glassmorphism animation effects created using html and css",
        thumbnail: "glassform.png",
        approx_date: "23/03/2021",
        keywords: ['html', 'css'],
        source_code: "https://codepen.io/manish202/pen/qBRWovQ",
        live_preview: "https://codepen.io/manish202/full/qBRWovQ",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 25,
        title: "glassmorphism animations",
        description: "glassmorphism animations with buttons, cards, clock using html, css and javascript",
        thumbnail: "glassmorphism.png",
        approx_date: "23/03/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/YzNPqXw",
        live_preview: "https://codepen.io/manish202/full/YzNPqXw",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 26,
        title: "shopnow php ecommerce",
        description: "this is the first php website i have created after watching youtube tutorials.",
        thumbnail: "shop-now.png",
        approx_date: "16/04/2021",
        keywords: ['html','php','css','javascript','jquery','okzoom','owl carousel'],
        source_code: "https://github.com/manish202/shopnow-php-ecommerce",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 27,
        title: "free web templates",
        description: "this site provide free web templates, its just a static website.",
        thumbnail: "freewebtemp.png",
        approx_date: "09/06/2021",
        keywords: ['html','css','bootstrap','javascript','jquery','aos'],
        source_code: "https://github.com/manish202/freewebtemplates",
        live_preview: "https://manish202.github.io/freewebtemplates/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 28,
        title: "quantum electronic site",
        description: "this is the static ecommerce site.",
        thumbnail: "quantum.png",
        approx_date: "23/06/2021",
        keywords: ['html','css','bootstrap','javascript','jquery'],
        source_code: "https://github.com/manish202/quantum",
        live_preview: "https://manish202.github.io/quantum/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 29,
        title: "anime js animation",
        description: "animation effects created using animejs with html, css and javascript",
        thumbnail: "animjs.png",
        approx_date: "28/07/2021",
        keywords: ['html', 'css', 'javascript', 'animejs'],
        source_code: "https://codepen.io/manish202/pen/XWREWMm",
        live_preview: "https://codepen.io/manish202/full/XWREWMm",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 30,
        title: "anime js heart animation",
        description: "heart animation created using animejs and javascript",
        thumbnail: "animjs2.png",
        approx_date: "28/07/2021",
        keywords: ['html', 'css', 'javascript', 'animejs'],
        source_code: "https://codepen.io/manish202/pen/xxdWGmx",
        live_preview: "https://codepen.io/manish202/full/xxdWGmx",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 31,
        title: "snake game with svg",
        description: "snake game built using svg and javascript",
        thumbnail: "snake.png",
        approx_date: "03/08/2021",
        keywords: ['html', 'css', 'svg', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/GRmBWYB",
        live_preview: "https://codepen.io/manish202/full/GRmBWYB",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 32,
        title: "scroll animation",
        description: "scroll based animation effects using javascript",
        thumbnail: "scroll_anim.png",
        approx_date: "03/08/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/oNWMwJj",
        live_preview: "https://codepen.io/manish202/full/oNWMwJj",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 33,
        title: "bitzhub clothing site",
        description: "static clothing website built using html, css and javascript",
        thumbnail: "bitzhub.png",
        approx_date: "12/08/2021",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/bitzhub",
        live_preview: "https://manish202.github.io/bitzhub/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 34,
        title: "fashion clothing site",
        description: "fashion clothing website using jquery and swiper js",
        thumbnail: "fashion.png",
        approx_date: "12/08/2021",
        keywords: ['html', 'css', 'javascript', 'jquery', 'swiper'],
        source_code: "https://github.com/manish202/clothing_site",
        live_preview: "https://manish202.github.io/clothing_site/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 35,
        title: "kirana store",
        description: "kirana store website built using html, css and jquery",
        thumbnail: "ashapuri_gro.png",
        approx_date: "20/08/2021",
        keywords: ['html','css','javascript','jquery'],
        source_code: "https://github.com/manish202/kirana-store",
        live_preview: "https://manish202.github.io/kirana-store/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 36,
        title: "online grocery store",
        description: "online grocery store with admin panel using php and mysql",
        thumbnail: "ashapurionline.png",
        approx_date: "15/10/2021",
        keywords: ['html','php','css','javascript','jquery','mysql'],
        source_code: "https://github.com/manish202/ashapurionline/tree/main/grocery",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 37,
        title: "dna animation",
        description: "dna animation created using html and css",
        thumbnail: "dna_anim.png",
        approx_date: "20/12/2021",
        keywords: ['html', 'css'],
        source_code: "https://codepen.io/manish202/pen/poWwQVO",
        live_preview: "https://codepen.io/manish202/full/poWwQVO",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 38,
        title: "bootstrap website",
        description: "responsive website design using bootstrap and javascript",
        thumbnail: "bt_design.png",
        approx_date: "20/12/2021",
        keywords: ['html', 'css', 'bootstrap', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/VwMWqZp",
        live_preview: "https://codepen.io/manish202/full/VwMWqZp",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 39,
        title: "html css animation",
        description: "creative animation effects using html and css",
        thumbnail: "css_anim4.png",
        approx_date: "20/12/2021",
        keywords: ['html', 'css'],
        source_code: "https://codepen.io/manish202/pen/BawZvwG",
        live_preview: "https://codepen.io/manish202/full/BawZvwG",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 40,
        title: "random animation",
        description: "random animation effects created using html and css",
        thumbnail: "rand_anim.png",
        approx_date: "27/01/2022",
        keywords: ['html', 'css'],
        source_code: "https://codepen.io/manish202/pen/mdqyabd",
        live_preview: "https://codepen.io/manish202/full/mdqyabd",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 41,
        title: "list of projects",
        description: "created webpage for showing my all projects",
        thumbnail: "all_projects.png",
        approx_date: "30/01/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/projects",
        live_preview: "https://manish202.github.io/projects/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 42,
        title: "gold jewellery",
        description: "gold jewellery website built using html, css and javascript",
        thumbnail: "gold.png",
        approx_date: "30/01/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/gold",
        live_preview: "https://manish202.github.io/gold/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 43,
        title: "meme api site",
        description: "using meme api with javascript",
        thumbnail: "memeapi.png",
        approx_date: "31/01/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/meme-api",
        live_preview: "https://manish202.github.io/meme-api/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 44,
        title: "first react website",
        description: "this is my first react website.",
        thumbnail: "first_react.png",
        approx_date: "09/02/2022",
        keywords: ['html', 'css', 'bootstrap', 'javascript', 'react', 'react-router-dom'],
        source_code: "https://github.com/manish202/FirstReactWebsite",
        live_preview: "https://manish202.github.io/FirstReactWebsite/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 45,
        title: "online blog website",
        description: "blog website with admin panel using php and mysql",
        thumbnail: "ashapuri_blog.png",
        approx_date: "18/02/2022",
        keywords: ['html','php','css','javascript','jquery','mysql'],
        source_code: "https://github.com/manish202/ashapurionline/tree/main/blog",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 46,
        title: "bootstrap 5 & git-github",
        description: "learning bootstrap 5 and git-github",
        thumbnail: "bt5.png",
        approx_date: "25/02/2022",
        keywords: ['html', 'css', 'bootstrap'],
        source_code: "https://github.com/manish202/bt5",
        live_preview: "https://manish202.github.io/bt5/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 47,
        title: "cat api in react",
        description: "using cat api in react app with infinite scroll",
        thumbnail: "catapi.png",
        approx_date: "27/02/2022",
        keywords: ['html', 'css', 'bootstrap', 'javascript', 'react'],
        source_code: "https://github.com/manish202/CatApi",
        live_preview: "https://manish202.github.io/CatApi/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 48,
        title: "live rotating fan animation",
        description: "rotating fan animation created using html and css",
        thumbnail: "fan.png",
        approx_date: "23/03/2022",
        keywords: ['html', 'css'],
        source_code: "https://codepen.io/manish202/pen/ExoNyMN",
        live_preview: "https://codepen.io/manish202/full/ExoNyMN",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 49,
        title: "basic digital clock",
        description: "basic digital clock built using javascript",
        thumbnail: "clock2.png",
        approx_date: "26/03/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/MWrpvmg",
        live_preview: "https://codepen.io/manish202/full/MWrpvmg",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 50,
        title: "php basic crud no js",
        description: "basic php crud application without javascript",
        thumbnail: "basic_crud.png",
        approx_date: "18/06/2022",
        keywords: ['html','php','css','bootstrap','mysql'],
        source_code: "https://github.com/manish202/php_crud/tree/main/basic_ajax_crud_no_js",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 51,
        title: "php news blog (with cms)",
        description: "news blog cms built using php and mysql, procedural method, no javascript or jquery used!",
        thumbnail: "php_news_blog.png",
        approx_date: "19/06/2022",
        keywords: ['html','php','css','bootstrap','mysql'],
        source_code: "https://github.com/manish202/php_news_blog",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 52,
        title: "php basic crud with jquery",
        description: "crud application using jquery ajax and php",
        thumbnail: "ajax_crud.png",
        approx_date: "22/06/2022",
        keywords: ['html','php','css','bootstrap','javascript','jquery','mysql'],
        source_code: "https://github.com/manish202/php_crud/tree/main/jquery_ajax_crud",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 53,
        title: "auto number increment",
        description: "auto number increment animation using javascript",
        thumbnail: "auto_num_inc.png",
        approx_date: "24/06/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/QWQeGzM",
        live_preview: "https://codepen.io/manish202/full/QWQeGzM",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 54,
        title: "react php mysql api crud",
        description: "react crud app with php mysql api backend",
        thumbnail: "react-php-mysql-api-crud.png",
        approx_date: "27/06/2022",
        keywords: ['html','css','bootstrap','javascript','react','php','mysql','react-router-dom','react-toastify'],
        source_code: "https://github.com/manish202/react_php_mysql_api_crud",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 55,
        title: "react todo list",
        description: "react todo list application using bootstrap 5",
        thumbnail: "reactbt5.png",
        approx_date: "03/07/2022",
        keywords: ['html','css','bootstrap','javascript','react'],
        source_code: "https://github.com/manish202/react_crud",
        live_preview: "https://manish202.github.io/react_crud/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 56,
        title: "react checkout cart page",
        description: "checkout cart ui built using react and mui",
        thumbnail: "reactcart.png",
        approx_date: "09/07/2022",
        keywords: ['html','css','javascript','react','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material'],
        source_code: "https://github.com/manish202/react_cart",
        live_preview: "https://manish202.github.io/react_cart/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 57,
        title: "random movies api in react",
        description: "react app showing random movies using api",
        thumbnail: "movieapi.png",
        approx_date: "12/07/2022",
        keywords: ['html','css','javascript','react'],
        source_code: "https://github.com/manish202/random-movies",
        live_preview: "https://manish202.github.io/random-movies/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 58,
        title: "news api with react",
        description: "react news application using api",
        thumbnail: "newsapi.png",
        approx_date: "13/07/2022",
        keywords: ['html','css','javascript','react','@emotion/react','@emotion/styled','@mui/material'],
        source_code: "https://github.com/manish202/react-news-api",
        live_preview: "https://manish202.github.io/react-news-api/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 59,
        title: "react firebase project",
        description: "react project using firebase",
        thumbnail: "firebase-react.png",
        approx_date: "16/07/2022",
        keywords: ['html','css','javascript','react','react-router-dom','firebase'],
        source_code: "https://github.com/manish202/firebase-auth",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 60,
        title: "manishpay with react",
        description: "react based simple ui project",
        thumbnail: "manishpay.png",
        approx_date: "19/07/2022",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom'],
        source_code: "https://github.com/manish202/manishpay",
        live_preview: "https://manish202.github.io/manishpay/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 61,
        title: "mern auth project",
        description: "mern stack authentication project using jwt and bcryptjs",
        thumbnail: "mern-auth.png",
        approx_date: "24/07/2022",
        keywords: ['html','css','javascript','react','react-cookie','react-router-dom','bcryptjs','node','express','mongodb','mongoose','jsonwebtoken','cors','dotenv'],
        source_code: "https://github.com/manish202/mern-auth",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 62,
        title: "blinkit clone mern (no CMS)",
        description: "blinkit clone built using mern stack with location access",
        thumbnail: "blinkit.png",
        approx_date: "30/07/2022",
        keywords: ['html','css','javascript','react','react-router-dom','react-toastify','node','express','mongodb','mongoose','dotenv','swiper'],
        source_code: "https://github.com/manish202/blinkit_clone",
        live_preview: "https://blinkit-clone-mwfj.onrender.com/",
        highlighted: true,
        private_repo: false,
    },
    {
        id: 63,
        title: "pure js todo app",
        description: "todo application using pure javascript and localstorage",
        thumbnail: "purejstodo.png",
        approx_date: "28/08/2022",
        keywords: ['html','css','bootstrap','javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/todo",
        live_preview: "https://manish202.github.io/javascript-projects/todo/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 64,
        title: "js timers & clock",
        description: "javascript timers and clock project",
        thumbnail: "jsclock.png",
        approx_date: "29/08/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/timer",
        live_preview: "https://manish202.github.io/javascript-projects/timer/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 65,
        title: "js budget app",
        description: "budget app built using javascript and localstorage",
        thumbnail: "budgetapp.png",
        approx_date: "30/08/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/budgetapp",
        live_preview: "https://manish202.github.io/javascript-projects/budgetapp/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 66,
        title: "js calculator",
        description: "basic calculator built using javascript",
        thumbnail: "calculator.png",
        approx_date: "30/08/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/calculator",
        live_preview: "https://manish202.github.io/javascript-projects/calculator/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 67,
        title: "js carousel",
        description: "image carousel created using javascript",
        thumbnail: "carousel.png",
        approx_date: "30/08/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/carousel",
        live_preview: "https://manish202.github.io/javascript-projects/carousel/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 68,
        title: "random password generator",
        description: "random password generator using javascript",
        thumbnail: "passgen.png",
        approx_date: "03/09/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/pass_generator",
        live_preview: "https://manish202.github.io/javascript-projects/pass_generator/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 69,
        title: "js random color generator",
        description: "random color generator built using javascript",
        thumbnail: "colorgen.png",
        approx_date: "05/09/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/color_generator",
        live_preview: "https://manish202.github.io/javascript-projects/color_generator/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 70,
        title: "clock in chart format",
        description: "clock in chart format created using javascript",
        thumbnail: "chartclock.png",
        approx_date: "06/09/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/javascript-projects/tree/master/chart_clock",
        live_preview: "https://manish202.github.io/javascript-projects/chart_clock/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 71,
        title: "responsive dropdown menu",
        description: "responsive multiple dropdown navigation menu using javascript",
        thumbnail: "dropdown-nav.png",
        approx_date: "11/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/qBYLdaO",
        live_preview: "https://codepen.io/manish202/full/qBYLdaO",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 72,
        title: "multiplication table using js",
        description: "print multiplication table dynamically using javascript",
        thumbnail: "mult_table.png",
        approx_date: "19/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/wvjbEGx",
        live_preview: "https://codepen.io/manish202/full/wvjbEGx",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 73,
        title: "data converter like gb-kb",
        description: "data size converter built using javascript",
        thumbnail: "data_conv.png",
        approx_date: "20/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/poVXeWm",
        live_preview: "https://codepen.io/manish202/full/poVXeWm",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 74,
        title: "age calculator using js",
        description: "age calculator application using javascript logic",
        thumbnail: "age_calc.png",
        approx_date: "20/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/vYjqWxE",
        live_preview: "https://codepen.io/manish202/full/vYjqWxE",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 75,
        title: "time converter using js",
        description: "time unit converter built using javascript",
        thumbnail: "time_conv.png",
        approx_date: "20/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/vYjqpVp",
        live_preview: "https://codepen.io/manish202/full/vYjqpVp",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 76,
        title: "tick tack toe logic",
        description: "tic tac toe game logic implemented using javascript",
        thumbnail: "ticktacktoe.png",
        approx_date: "21/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/JjvgGRd",
        live_preview: "https://codepen.io/manish202/full/JjvgGRd",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 77,
        title: "random dog images api",
        description: "random dog images fetched using public api",
        thumbnail: "dog_img_api.png",
        approx_date: "28/10/2022",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://codepen.io/manish202/pen/mdKJBmr",
        live_preview: "https://codepen.io/manish202/full/mdKJBmr",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 78,
        title: "react node fs crud",
        description: "Crud Operation In Json File Using Reactjs & NodeJs",
        thumbnail: "react-node-fs-crud.png",
        approx_date: "11/11/2022",
        keywords: ['html','css','javascript','react','react-toastify','node','cors'],
        source_code: "https://github.com/manish202/react_node_json_crud",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 79,
        title: "github users api",
        description: "react application fetching github users using api",
        thumbnail: "github-users-api.png",
        approx_date: "08/12/2022",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom','@mui/icons-material'],
        source_code: "https://github.com/manish202/github_users_api",
        live_preview: "https://github-users-api.onrender.com/",
        highlighted: true,
        private_repo: false,
    },
    {
        id: 80,
        title: "wordpress website",
        description: "wordpress based hair salon business website",
        thumbnail: "laima-unisex.png",
        approx_date: "30/12/2022",
        keywords: ['html','css','javascript','php','mysql','wordpress'],
        source_code: "https://github.com/manish202/laima_unisex_salon",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 81,
        title: "personal portfolio",
        description: "personal portfolio website built using html, css and javascript",
        thumbnail: "my-portfolio.png",
        approx_date: "04/01/2023",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/portfolio",
        live_preview: "https://manish202.github.io/portfolio/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 82,
        title: "onwardpass v1 (paytm)",
        description: "flight reservation website built using php and mysql with paytm payment gateway.",
        thumbnail: "onwardpass.png",
        approx_date: "08/01/2023",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v1",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 83,
        title: "php news blog 2 (with cms)",
        description: "php news blog website with custom cms, procedural method, no javascript or jquery, developed 2nd time for revision.",
        thumbnail: "php_news_blog2.png",
        approx_date: "22/05/2023",
        keywords: ['html','css','php','mysql'],
        source_code: "https://github.com/manish202/php_news_blog2",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 84,
        title: "restaurant website in react",
        description: "restaurant website built using react",
        thumbnail: "naans-curries.png",
        approx_date: "11/06/2023",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom'],
        source_code: "https://github.com/manish202/naans-curries",
        live_preview: "https://naans-and-curries.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 85,
        title: "hair salon in nextjs",
        description: "indulge hair salon website built using react and nextjs",
        thumbnail: "indulge.png",
        approx_date: "17/06/2023",
        keywords: ['html','css','javascript','react','next','serve'],
        source_code: "https://github.com/manish202/indulgestyle",
        live_preview: "https://indulgestyle.onrender.com/",
        highlighted: true,
        private_repo: true,
    },
    {
        id: 86,
        title: "startheria v1 (html)",
        description: "customized existing startheria web pages in html",
        thumbnail: "startheria.png",
        approx_date: "28/06/2023",
        keywords: ['html','css','javascript'],
        source_code: "https://github.com/manish202/startheria_v1",
        live_preview: "https://www.startheria.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 87,
        title: "personal portfolio",
        description: "my personal portfolio website.",
        thumbnail: "personal_portfolio.png",
        approx_date: "13/07/2023",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/my-portfolio",
        live_preview: "https://manish202.github.io/my-portfolio/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 88,
        title: "pwa, indexeddb etc...",
        description: "learing pwa, indexeddb, debouncing, and throttling concepts.",
        thumbnail: "pwa_indexdb_debouncing_throttling.png",
        approx_date: "30/07/2023",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/pwa_indexedDB_debouncing_throttling",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 89,
        title: "chrome extension",
        description: "basic chrome extension built using javascript",
        thumbnail: "chrome_extension.png",
        approx_date: "01/08/2023",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/hello_world_chrome_extension",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 90,
        title: "react mui todo app",
        description: "todo application built using react and material ui",
        thumbnail: "react_mui_todo_app.png",
        approx_date: "12/08/2023",
        keywords: ['html','css','javascript','react','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material'],
        source_code: "https://github.com/manish202/react-todo-with-mui",
        live_preview: "https://react-todo-app-o1je.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 91,
        title: "react mui weather app",
        description: "weather application built using react and material ui",
        thumbnail: "weather-app.png",
        approx_date: "13/08/2023",
        keywords: ['html','css','javascript','react','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material'],
        source_code: "https://github.com/manish202/weather-app-mui",
        live_preview: "https://react-weather-app-mui.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 92,
        title: "startheria v2 (php)",
        description: "customized existing startheria web pages in php",
        thumbnail: "startheria.png",
        approx_date: "04/09/2023",
        keywords: ['html','css','javascript','php'],
        source_code: "https://github.com/manish202/startheria_v2",
        live_preview: "https://www.startheria.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 93,
        title: "react music player app",
        description: "music player application built using react and material ui",
        thumbnail: "reactjs-music-player.png",
        approx_date: "29/09/2023",
        keywords: ['html','css','javascript','react','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material'],
        source_code: "https://github.com/manish202/reactjs-music-player",
        live_preview: "https://reactjs-music-player.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 94,
        title: "startheria v3 (php)",
        description: "customized existing startheria web pages in php as client requirement.",
        thumbnail: "startheria.png",
        approx_date: "03/10/2023",
        keywords: ['html', 'css', 'javascript', 'php'],
        source_code: "https://github.com/manish202/startheria_v3",
        live_preview: "https://www.startheria.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 95,
        title: "onwardpass v2 (phonepe)",
        description: "flight reservation website built using php and mysql with phonepe payment gateway.",
        thumbnail: "onwardpass.png",
        approx_date: "11/10/2023",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v2",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 96,
        title: "onwardpass v3 (paytm)",
        description: "flight reservation website built using php and mysql with paytm payment gateway. improved version of v1",
        thumbnail: "onwardpass.png",
        approx_date: "13/10/2023",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v3",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 97,
        title: "onwardpass v4 (phonepe)",
        description: "flight reservation website built using php and mysql with phonepe payment gateway. improved version of v2",
        thumbnail: "onwardpass.png",
        approx_date: "16/10/2023",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v4",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 98,
        title: "react video player app",
        description: "video player application built using react and material ui",
        thumbnail: "reactjs-video-player.png",
        approx_date: "18/10/2023",
        keywords: ['html','css','javascript','react','@emotion/react','@emotion/styled','@mui/icons-material','@mui/material'],
        source_code: "https://github.com/manish202/reactjs-video-player",
        live_preview: "https://reactjs-video-player.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 99,
        title: "onwardproof (stripe)",
        description: "flight reservation website built using php and mysql with stripe payment gateway.",
        thumbnail: "onwardpass.png",
        approx_date: "21/10/2023",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardproof",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 100,
        title: "laravel news blog website",
        description: "my first laravel project. news blog website with custom cms and session based auth.",
        thumbnail: "laravel_news_blog.png",
        approx_date: "27/10/2023",
        keywords: ['html','css','bootstrap','php','mysql','laravel'],
        source_code: "https://github.com/manish202/laravel_news_blog",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 101,
        title: "blinkit ecom mern (with cms)",
        description: "blinkit style ecommerce application built using mern stack with custom cms",
        thumbnail: "blinkit-ecom.png",
        approx_date: "16/11/2023",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom','react-toastify','react-redux','@reduxjs/toolkit','node','express','mongodb','mongoose','bcryptjs','body-parser','cors','dotenv','jsonwebtoken','multer'],
        source_code: "https://github.com/manish202/blinkit_ecom",
        live_preview: "https://blinkit-ecom-88bh.onrender.com/",
        highlighted: true,
        private_repo: true,
    },
    {
        id: 102,
        title: "restaurant site with nextjs",
        description: "restaurant website converted to nextjs",
        thumbnail: "nextjs-restaurant.png",
        approx_date: "19/11/2023",
        keywords: ['html','css','bootstrap','javascript','react','next'],
        source_code: "https://github.com/manish202/nextjs-restaurant",
        live_preview: "https://nextjs-restaurant.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 103,
        title: "onwardpass v5 (razorpay)",
        description: "flight reservation website built using php and mysql with razorpay payment gateway.",
        thumbnail: "onwardpass.png",
        approx_date: "24/12/2023",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v5",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 104,
        title: "my todo app",
        description: "created basic react todo app with babel, webpack manual configuration.",
        thumbnail: "my-todo-app.png",
        approx_date: "29/12/2023",
        keywords: ['html','css','bootstrap','javascript','react','@reduxjs/toolkit','react-redux','@babel/core','@babel/preset-env','@babel/preset-react','babel-loader','css-loader','html-webpack-plugin','mini-css-extract-plugin','style-loader','webpack','webpack-cli','webpack-dev-server'],
        source_code: "https://github.com/manish202/my-todo-app",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 105,
        title: "startheria v4 (php)",
        description: "customized existing startheria web pages in php as client requirement.",
        thumbnail: "startheria.png",
        approx_date: "03/01/2024",
        keywords: ['html', 'css', 'javascript', 'php'],
        source_code: "https://github.com/manish202/startheria_v4",
        live_preview: "https://www.startheria.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 106,
        title: "web dev revision",
        description: "Revision of web development from 24/03/2024 to 14/04/2024",
        thumbnail: "web_dev_revision.png",
        approx_date: "24/03/2024",
        keywords: ['html','css','sass','bootstrap','javascript','jquery','typescript','git-github','react','php','mysql','node','express','mongodb','mongoose'],
        source_code: "https://github.com/manish202/web_dev_revision",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 107,
        title: "react multiple projects",
        description: "collection of react projects including todo app, accordion, github users and shopping cart",
        thumbnail: "todoapp_accordion_githubusers_shoppingcart.png",
        approx_date: "15/04/2024",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom'],
        source_code: "https://github.com/manish202/react_projects",
        live_preview: "https://manish202.github.io/react_projects/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 108,
        title: "mern auth project 2",
        description: "mern stack authentication project using jwt and bcryptjs, revision.",
        thumbnail: "mern_project.png",
        approx_date: "17/04/2024",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom','node','express','mongodb','mongoose','bcryptjs','cookie-parser','dotenv','jsonwebtoken'],
        source_code: "https://github.com/manish202/mern_project",
        live_preview: "https://mern-project-9xcw.onrender.com/",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 109,
        title: "styled component practice",
        description: "practice project for styled components in react",
        thumbnail: "styled-compo.png",
        approx_date: "21/04/2024",
        keywords: ['html','css','javascript','react','react-router-dom','styled-components'],
        source_code: "https://github.com/manish202/styled-compo-practice",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 110,
        title: "react static e-commerce",
        description: "static ecommerce website built using react",
        thumbnail: "react-static-ecom.png",
        approx_date: "22/04/2024",
        keywords: ['html','css','javascript','react','@auth0/auth0-react','react-icons','react-router-dom','styled-components'],
        source_code: "https://github.com/manish202/react-static-ecom",
        live_preview: "https://react-static-ecom.onrender.com/",
        highlighted: true,
        private_repo: false,
    },
    {
        id: 111,
        title: "redux toolkit practice",
        description: "Redux And Redux-Toolkit Practice.",
        thumbnail: "redux_toolkit.png",
        approx_date: "28/04/2024",
        keywords: ['html','css','javascript','react','redux','react-redux','@reduxjs/toolkit'],
        source_code: "https://github.com/manish202/redux_toolkit_practice",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 112,
        title: "nextjs tutorial pages router",
        description: "Nextjs pages router tutorial completed from youtube.",
        thumbnail: "nextjs_tutorial.png",
        approx_date: "29/04/2024",
        keywords: ['html','css','javascript','react','next'],
        source_code: "https://github.com/manish202/nextjs_tutorial",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 113,
        title: "nextjs tutorial app router",
        description: "Nextjs app router tutorial completed from youtube.",
        thumbnail: "nextjs_tutorial2.png",
        approx_date: "30/04/2024",
        keywords: ['html','css','javascript','react','next','react-icons'],
        source_code: "https://github.com/manish202/nextjs_tutorial_2",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 114,
        title: "graphql exploration project",
        description: "graphql exploration project with react and mongodb",
        thumbnail: "first_graphql_project.png",
        approx_date: "08/05/2024",
        keywords: ['html','css','bootstrap','javascript','react','react-router-dom','@apollo/client','node','mongodb','mongoose','graphql','apollo-server','apollo-server-core','bcryptjs','jsonwebtoken'],
        source_code: "https://github.com/manish202/first_fraphql_project",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 115,
        title: "personal portfolio",
        description: "personal portfolio website",
        thumbnail: "best_portfolio.png",
        approx_date: "23/05/2024",
        keywords: ['html', 'css', 'javascript'],
        source_code: "https://github.com/manish202/best_portfolio",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 116,
        title: "onwardpass v6 (phonepe)",
        description: "flight reservation website built using php and mysql with phonepe payment gateway. improved version of v4",
        thumbnail: "onwardpass.png",
        approx_date: "02/07/2024",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v6",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 117,
        title: "laravel tutorial",
        description: "laravel tutorial completed from yahoo baba youtube channel. Date-05/07/2024 to 16/07/2024",
        thumbnail: "laravel_tutorial_from_yt.png",
        approx_date: "05/07/2024",
        keywords: ['html','css','javascript','php','mysql','laravel'],
        source_code: "https://github.com/manish202/laravel_tutorial",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 118,
        title: "onwardpass v7 (phonepe)",
        description: "flight reservation website built using php and mysql with phonepe payment gateway. improved version of v6",
        thumbnail: "onwardpass.png",
        approx_date: "24/09/2024",
        keywords: ['html','css','javascript','jquery','php','mysql'],
        source_code: "https://github.com/manish202/onwardpass_v7",
        live_preview: "https://onwardpass.com/",
        highlighted: true,
        private_repo: true,
    },
    {
        id: 119,
        title: "onwardpass v8 (phonepe)",
        description: "flight reservation website built using php and mysql with phonepe payment gateway. tried to convert v7 into laravel",
        thumbnail: "onwardpass.png",
        approx_date: "15/10/2024",
        keywords: ['html','css','javascript','jquery','php','mysql','laravel'],
        source_code: "https://github.com/manish202/onwardpass_v8",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 120,
        title: "travelport v1",
        description: "Started working on travelport api from 16/10/2024 for onwardpass",
        thumbnail: "travelport_api.png",
        approx_date: "16/10/2024",
        keywords: ['html','css','javascript','axios','node','express','hbs','joi','moment-timezone','xml-formatter','xmldom','xpath','dotenv'],
        source_code: "https://github.com/manish202/travelport_v1",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 121,
        title: "travelport schema",
        description: "exploring travelport api schema and documentation",
        thumbnail: "travelport_schema.png",
        approx_date: "20/10/2024",
        keywords: [],
        source_code: "https://github.com/manish202/travelport_schema",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 122,
        title: "travelport work",
        description: "travelport api implementation and experiments for onwardpass",
        thumbnail: "travelport_api_work.png",
        approx_date: "15/11/2024",
        keywords: ['html','css','javascript','axios','node','express','hbs','joi','moment-timezone','xml-formatter','xmldom','xpath','dotenv'],
        source_code: "https://github.com/manish202/travelport_work",
        live_preview: null,
        highlighted: false,
        private_repo: true,
    },
    {
        id: 123,
        title: "onwardpass v9 (phonepe)",
        description: "converted onwardpass v7 & v8 to nodejs with travelport api & whatsapp chat bot using hbs template engine",
        thumbnail: "onwardpass.png",
        approx_date: "26/11/2024",
        keywords: ['html','css','javascript','axios','bcrypt','cookie-parser','node','express','hbs','jsonwebtoken','knex','moment-timezone','mysql2','node-cron','xml-formatter','xmldom','xpath','dotenv'],
        source_code: "https://github.com/manish202/onwardpass_v9",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 124,
        title: "onwardpass v10 (phonepe)",
        description: "converted onwardpass v9 to nodejs with travelport api & whatsapp chat bot using ejs template engine",
        thumbnail: "onwardpass.png",
        approx_date: "13/01/2025",
        keywords: ['html','css','javascript','axios','bcrypt','cookie-parser','node','express','ejs','jsonwebtoken','knex','luxon','moment-timezone','mysql2','node-cron','nodemailer','xml-formatter','xmldom','xpath','dotenv'],
        source_code: "https://github.com/manish202/onwardpass_v10",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 125,
        title: "onwardpass v11 (phonepe)",
        description: "Production Version. improved version of onwardpass_v10",
        thumbnail: "onwardpass.png",
        approx_date: "25/01/2025",
        keywords: ['html','css','javascript','axios','bcrypt','cookie-parser','node','express','ejs','jsonwebtoken','knex','luxon','moment-timezone','mysql2','node-cron','nodemailer','xml-formatter','xmldom','xpath','dotenv'],
        source_code: "https://github.com/manish202/onwardpass_v11",
        live_preview: "https://onwardpass.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 126,
        title: "data tables tabulator js",
        description: "Create Tables with dynamic data, export data in excel, pdf, csv format. D 19/10/2025",
        thumbnail: "data_tables_tabulatorjs.png",
        approx_date: "19/10/2025",
        keywords: ['html','css','javascript','node','express','mongodb','mongoose'],
        source_code: "https://github.com/manish202/data_tables_tabulator_js",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 127,
        title: "node express mongo crud",
        description: "basic crud operation with node, express, mongo and pagination. D 19/10/2025",
        thumbnail: "node_express_mongo_basic_crud.png",
        approx_date: "19/10/2025",
        keywords: ['html','css','javascript','ejs','node','express','mongodb','mongoose','mongoose-paginate-v2'],
        source_code: "https://github.com/manish202/node_express_mongo_pagination_crud",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 128,
        title: "session token hybrid oauth",
        description: "session based, token based, hybrid (session + token), oauth authentication D 20/10/2025",
        thumbnail: "hybrid_auth.png",
        approx_date: "20/10/2025",
        keywords: ['html','css','javascript','bcryptjs','cookie-parser','ejs','node','express','express-session','jsonwebtoken','mongodb','mongoose','passport','passport-google-oauth20'],
        source_code: "https://github.com/manish202/session_token_hybrid_oauth_authentication",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 129,
        title: "node express mongo api",
        description: "user register, login, logout, students data crud using api.",
        thumbnail: "node_express_mongo_api_crud.png",
        approx_date: "20/10/2025",
        keywords: ['html','css','javascript','bcryptjs','node','express','mongodb','mongoose','express-rate-limit','helmet','jsonwebtoken','multer'],
        source_code: "https://github.com/manish202/node_express_mongo_api_crud",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 130,
        title: "node express news blog",
        description: "created news blog cms project using nodejs, expressjs, mongodb from yahubaba youtube channel.",
        thumbnail: "node_express_news_blog.png",
        approx_date: "21/10/2025",
        keywords: ['html','css','javascript','bcryptjs','node','express','mongodb','mongoose','compression','cookie-parser','ejs','express-ejs-layouts','express-minify-html-terser','express-validator','jsonwebtoken','mongoose-paginate-v2','multer','node-cache','slugify'],
        source_code: "https://github.com/manish202/node_express_mongo_news_blog",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 131,
        title: "tanstack query crud",
        description: "tanstack query crud operation + infinite scrolling implemented.",
        thumbnail: "tanstack_query.png",
        approx_date: "22/11/2025",
        keywords: ['html','css','bootstrap','javascript','react','@tanstack/react-query','@tanstack/react-query-devtools','react-intersection-observer','react-router'],
        source_code: "https://github.com/manish202/tanstack_query_crud",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 132,
        title: "auth0 simple project",
        description: "auth0 simple project completed.",
        thumbnail: "auth0.png",
        approx_date: "23/11/2025",
        keywords: ['html','css','bootstrap','javascript','react','@auth0/auth0-react','react-router'],
        source_code: "https://github.com/manish202/auth0_simple_project",
        live_preview: null,
        highlighted: false,
        private_repo: false,
    },
    {
        id: 133,
        title: "nomadifly adventure",
        description: "Its a static tourism website built-in nextjs",
        thumbnail: "nomadiflyadventure.png",
        approx_date: "13/01/2026",
        keywords: ['html','css','javascript','react','next'],
        source_code: "https://github.com/manish202/nomadiflyadventure",
        live_preview: "https://www.nomadiflyadventure.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 134,
        title: "the pizza pro",
        description: "Its a static website built-in nextjs",
        thumbnail: "thepizzapro.png",
        approx_date: "18/01/2026",
        keywords: ['html','css','javascript','react','next'],
        source_code: "https://github.com/manish202/thepizzapro",
        live_preview: "https://thepizzapro.onrender.com",
        highlighted: false,
        private_repo: false,
    },
    {
        id: 135,
        title: "nomadifly in nextjs",
        description: "Its a static website built-in nextjs",
        thumbnail: "nomadifly_in_core_php.png",
        approx_date: "23/01/2026",
        keywords: ['html','css','javascript','react','next','react-icons','styled-components'],
        source_code: "https://github.com/manish202/nomadifly_nextjs",
        live_preview: "https://nomadifly.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 136,
        title: "nomadifly in core php",
        description: "Its a static website built-in core php",
        thumbnail: "nomadifly_in_core_php.png",
        approx_date: "27/01/2026",
        keywords: ['html','css','javascript','jquery','php'],
        source_code: "https://github.com/manish202/nomadifly_corephp",
        live_preview: "https://nomadifly.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 137,
        title: "nomadifly in laravel",
        description: "Its a static website built-in laravel",
        thumbnail: "nomadifly_in_core_php.png",
        approx_date: "02/02/2026",
        keywords: ['html','css','javascript','jquery','php','mysql','laravel'],
        source_code: "https://github.com/manish202/nomadifly_laravel",
        live_preview: "https://nomadifly.com/",
        highlighted: false,
        private_repo: true,
    },
    {
        id: 138,
        title: "blinkit store backend",
        description: "Its a backend of blinkit store MERN project",
        thumbnail: "blinkit_store.png",
        approx_date: "05/02/2026",
        keywords: ['node','express','mongodb','mongoose','bcryptjs','cloudinary','cookie-parser','cors','dotenv','express-rate-limit','helmet','jsonwebtoken','multer','nodemailer','stripe','winston','zod'],
        source_code: "https://github.com/manish202/blinkit_store_backend",
        live_preview: "https://blinkit-store.onrender.com/",
        highlighted: true,
        private_repo: true,
    },
    {
        id: 139,
        title: "blinkit store frontend",
        description: "Its a frontend of blinkit store MERN project",
        thumbnail: "blinkit_store.png",
        approx_date: "23/02/2026",
        keywords: ['html','css','bootstrap','javascript','react','react-icons','react-intersection-observer','zod','swiper','styled-components','react-toastify','react-router','react-google-charts','react-redux','@reduxjs/toolkit','@tanstack/react-query','axios'],
        source_code: "https://github.com/manish202/blinkit_store_frontend",
        live_preview: "https://blinkit-store.onrender.com/",
        highlighted: true,
        private_repo: true,
    },
]
export default projects;